export enum RARITY {
  COMMON,
  RARE,
  LEGENDARY,
}

export enum GIZMOS {
  NONE,
}

export const GUN_LOOT_MAP = [
  {
    id: 0,
    name: "Makeshift Revolver",
    rarity: RARITY.COMMON,
    spriteName: "gun-revolver",
    pathToWebp: "/webps/games/cowpoke-gun-revolver.webp",
    addDmg: 0,
    addHealth: 0,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 1,
    name: "Trusty Revolver",
    rarity: RARITY.RARE,
    spriteName: "gun-revolver",
    pathToWebp: "/webps/games/cowpoke-gun-revolver.webp",
    addDmg: 1,
    addHealth: 0,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 2,
    name: "Cowpoke Jack's Revolver",
    rarity: RARITY.LEGENDARY,
    spriteName: "gun-revolver",
    pathToWebp: "/webps/games/cowpoke-gun-revolver.webp",
    addDmg: 3,
    addHealth: 2,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 3,
    name: "Rusty Handcannon",
    rarity: RARITY.COMMON,
    spriteName: "gun-handcannon",
    pathToWebp: "/webps/games/cowpoke-gun-handcannon.webp",
    addDmg: 1,
    addHealth: 0,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 4,
    name: "Ol' Reliable Handcannon",
    rarity: RARITY.RARE,
    spriteName: "gun-handcannon",
    pathToWebp: "/webps/games/cowpoke-gun-handcannon.webp",
    addDmg: 3,
    addHealth: 0,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 5,
    name: "Big Bertha",
    rarity: RARITY.LEGENDARY,
    spriteName: "gun-handcannon",
    pathToWebp: "/webps/games/cowpoke-gun-handcannon.webp",
    addDmg: 4,
    addHealth: 0,
    addCombat: 1,
    addElement: 1,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 6,
    name: "Busted Crooked Revolver",
    rarity: RARITY.COMMON,
    spriteName: "gun-crooked-revolver",
    pathToWebp: "/webps/games/cowpoke-gun-crooked-revolver.webp",
    addDmg: 0,
    addHealth: 0,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 7,
    name: "Sidewards Revolver",
    rarity: RARITY.RARE,
    spriteName: "gun-crooked-revolver",
    pathToWebp: "/webps/games/cowpoke-gun-crooked-revolver.webp",
    addDmg: 2,
    addHealth: 0,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 8,
    name: "Ol' Sideshooter",
    rarity: RARITY.LEGENDARY,
    spriteName: "gun-crooked-revolver",
    pathToWebp: "/webps/games/cowpoke-gun-crooked-revolver.webp",
    addDmg: 4,
    addHealth: 0,
    addCombat: 0,
    addElement: 2,
    extraGizmo: GIZMOS.NONE,
  },
];

export const HAT_LOOT_MAP = [
  {
    id: 0,
    name: "Deputy Hat",
    rarity: RARITY.COMMON,
    spriteName: "hat-sherif",
    pathToWebp: "/webps/games/cowpoke-hat-sherif.webp",
    addDmg: 0,
    addHealth: 1,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 1,
    name: "Sheriff Hat",
    rarity: RARITY.RARE,
    spriteName: "hat-sherif",
    pathToWebp: "/webps/games/cowpoke-hat-sherif.webp",
    addDmg: 0,
    addHealth: 2,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 2,
    name: "Cowpoke Jack's Hat",
    rarity: RARITY.LEGENDARY,
    spriteName: "hat-sherif",
    pathToWebp: "/webps/games/cowpoke-hat-sherif.webp",
    addDmg: 1,
    addHealth: 3,
    addCombat: 1,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 3,
    name: "Lazy Bandito Hat",
    rarity: RARITY.COMMON,
    spriteName: "hat-bandito",
    pathToWebp: "/webps/games/cowpoke-hat-bandito.webp",
    addDmg: 0,
    addHealth: 1,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 4,
    name: "Career Bandito Hat",
    rarity: RARITY.RARE,
    spriteName: "hat-bandito",
    pathToWebp: "/webps/games/cowpoke-hat-bandito.webp",
    addDmg: 0,
    addHealth: 2,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 5,
    name: "Bandito Earl's Hat",
    rarity: RARITY.LEGENDARY,
    spriteName: "hat-bandito",
    pathToWebp: "/webps/games/cowpoke-hat-bandito.webp",
    addDmg: 1,
    addHealth: 3,
    addCombat: 0,
    addElement: 1,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 6,
    name: "Dusty Warlock Hat",
    rarity: RARITY.COMMON,
    spriteName: "hat-wizard",
    pathToWebp: "/webps/games/cowpoke-hat-wizard.webp",
    addDmg: 0,
    addHealth: 1,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 7,
    name: "Sideshow Wizard Hat",
    rarity: RARITY.RARE,
    spriteName: "hat-wizard",
    pathToWebp: "/webps/games/cowpoke-hat-wizard.webp",
    addDmg: 0,
    addHealth: 2,
    addCombat: 0,
    addElement: 1,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 8,
    name: "Magical Wizard Hat",
    rarity: RARITY.LEGENDARY,
    spriteName: "hat-wizard",
    pathToWebp: "/webps/games/cowpoke-hat-wizard.webp",
    addDmg: 0,
    addHealth: 3,
    addCombat: 0,
    addElement: 4,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 9,
    name: "Common Christmas Hat",
    rarity: RARITY.COMMON,
    spriteName: "hat-santa",
    pathToWebp: "/webps/games/cowpoke-hat-santa.webp",
    addDmg: 0,
    addHealth: 1,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 10,
    name: "Santa's lil Helper Hat",
    rarity: RARITY.RARE,
    spriteName: "hat-santa",
    pathToWebp: "/webps/games/cowpoke-hat-santa.webp",
    addDmg: 0,
    addHealth: 2,
    addCombat: 0,
    addElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 11,
    name: "Cowpoke Santa's Hat",
    rarity: RARITY.LEGENDARY,
    spriteName: "hat-santa",
    pathToWebp: "/webps/games/cowpoke-hat-santa.webp",
    addDmg: 1,
    addHealth: 3,
    addCombat: 2,
    addElement: 1,
    extraGizmo: GIZMOS.NONE,
  },
];
