export const RARITY = {
  COMMON: 0,
  RARE: 1,
  LEGENDARY: 2,
};

export const GIZMOS = {
  NONE: 0,
};

export const GUN_LOOT_MAP = [
  {
    id: 0,
    name: "Makeshift Revolver",
    rarity: RARITY.COMMON,
    spriteName: "gun-revolver",
    addDmg: 0,
    addHealth: 0,
    addSpeed: 1,
    addCombat: 0,
    addElement: 0,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 1,
    name: "Trusty Revolver",
    rarity: RARITY.RARE,
    spriteName: "gun-revolver",
    addDmg: 1,
    addHealth: 0,
    addSpeed: 1,
    addCombat: 0,
    addElement: 0,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 2,
    name: "Cowpoke Jack's Revolver",
    rarity: RARITY.LEGENDARY,
    spriteName: "gun-revolver",
    addDmg: 3,
    addHealth: 0,
    addSpeed: 1,
    addCombat: 0,
    addElement: 0,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 3,
    name: "Rusty Handcannon",
    rarity: RARITY.COMMON,
    spriteName: "gun-handcannon",
    addDmg: 1,
    addHealth: 0,
    addSpeed: -1,
    addCombat: 0,
    addElement: 0,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 4,
    name: "Ol' Reliable Handcannon",
    rarity: RARITY.RARE,
    spriteName: "gun-handcannon",
    addDmg: 3,
    addHealth: 0,
    addSpeed: -1,
    addCombat: 0,
    addElement: 0,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 5,
    name: "Big Bertha",
    rarity: RARITY.LEGENDARY,
    spriteName: "gun-handcannon",
    addDmg: 4,
    addHealth: 0,
    addSpeed: -1,
    addCombat: 0,
    addElement: 0,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
];

export const HAT_LOOT_MAP = [
  {
    id: 0,
    name: "Deputy Hat",
    rarity: RARITY.COMMON,
    spriteName: "hat-sherif",
    addDmg: 0,
    addHealth: 1,
    addSpeed: 0,
    addCombat: 0,
    addElement: 1,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 1,
    name: "Sheriff Hat",
    rarity: RARITY.RARE,
    spriteName: "hat-sherif",
    addDmg: 0,
    addHealth: 2,
    addSpeed: 0,
    addCombat: 0,
    addElement: 1,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 2,
    name: "Cowpoke Jack's Hat",
    rarity: RARITY.LEGENDARY,
    spriteName: "hat-sherif",
    addDmg: 0,
    addHealth: 3,
    addSpeed: 0,
    addCombat: 0,
    addElement: 1,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 3,
    name: "Lazy Bandito Hat",
    rarity: RARITY.COMMON,
    spriteName: "hat-bandito",
    addDmg: 0,
    addHealth: 1,
    addSpeed: 1,
    addCombat: 0,
    addElement: 0,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 4,
    name: "Career Bandito Hat",
    rarity: RARITY.RARE,
    spriteName: "hat-bandito",
    addDmg: 0,
    addHealth: 2,
    addSpeed: 1,
    addCombat: 0,
    addElement: 0,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
  {
    id: 5,
    name: "Bandito Earl's Hat",
    rarity: RARITY.LEGENDARY,
    spriteName: "hat-bandito",
    addDmg: 0,
    addHealth: 3,
    addSpeed: 1,
    addCombat: 0,
    addElement: 0,
    radiusSpeed: 0,
    radiusCombat: 0,
    radiusElement: 0,
    extraGizmo: GIZMOS.NONE,
  },
];
