name: Deploy website to Firebase on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: <DEBUG> List Contents of webps Folder Before Cleanup
        run: ls -la public/webps

      - name: Remove Unnecessary Files From Build
        run: |
          rm -rf .git*
          rm -rf .github 
          rm -rf README*
          rm -rf LICENSE*
          rm -rf ./*/*.md
          rm -rf ./*/*.png # We use the webp for images, not pngs!
          rm -rf **/*.py 
          rm -rf **/*.pyc
          rm -rf .DS_Store # Remove macOS specific hidden files
          rm -rf node_modules # Remove node_modules directory
          rm -rf .next # Remove Next.js build artifacts
          rm -rf coverage # Remove coverage reports
          rm -rf tests # Remove test files
          rm -rf **/*.test.js # Remove test files
          rm -rf **/*.spec.js # Remove spec files
          rm -rf **/*.config.js # Remove configuration files
          rm -rf **/*.config.ts # Remove TypeScript configuration files
          rm -rf **/*.log # Remove log files

      - name: <DEBUG> List Contents of webps Folder After Cleanup
        run: ls -la public/webps

      - name: Build and Export Next.js Application
        run: |
          npm install
          npm run build
        env:
          NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}

      - name: <DEBUG> List Contents of webps Folder After Build
        run: ls -la out/webps

      - name: Deploy Site to Firebase Hosting
        run: firebase deploy --only hosting --project black-hole-reject --token "${{ secrets.FIREBASE_TOKEN }}"
