name: Deploy website to Firebase on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build and Export Next.js Application
        run: npm run build

      - name: Remove Unnecessary Files From Build Output Directory
        run: |
          cd out  # Change to the build output directory
          find . -name "*.md" -delete
          find . -name "*.png" -delete
          find . -name "*.py" -delete
          find . -name "*.pyc" -delete
          find . -name "*.log" -delete
          find . -name "*.test.js" -delete
          find . -name "*.spec.js" -delete
          find . -name ".DS_Store" -delete

      - name: Deploy Site to Firebase Hosting
        run: firebase deploy --only hosting --project black-hole-reject --token "${{ secrets.FIREBASE_TOKEN }}"
